config/routes.rb
Rails.application.routes.draw do
  root to: 'memes#index'
  resources :memes
  post '/comments/new', to: 'comments#create'
  get '/popular', to: 'memes#popular'
  # Votes
  post '/votes/new', to: 'votes#create'
  post '/votes/unvote', to: 'votes#unvote'

  devise_for :users
  get '/my_profile', to: 'users#show'
  get '/categories', to: 'memes#categories'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :memes
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :meme
end

app/models/meme.rb
class Meme < ApplicationRecord
  self.inheritance_column = :_type_disabled
  VALID_TYPE = ['image', 'gif'].freeze

  validates :title, :url_source, presence: true
  validates :title, uniqueness: true
  validates :type, inclusion: { in: VALID_TYPE, message: "should be image or gif" }
  validates :url_source, format: { with: /\.(jpg|png|gif)\z/, message: "Image should be jpg, png or gif" }

  belongs_to :category
  has_and_belongs_to_many :tags
  belongs_to :owner, class_name: "User", counter_cache: true
  has_many :votes
  has_many :comments
  has_many :users, through: :votes
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :memes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, presence: true, uniqueness: true

  has_and_belongs_to_many :memes
  has_many :comments
  has_many :memes, through: :comments
  has_many :votes
  has_many :memes, through: :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :meme, counter_cache:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(body: params[:body], meme_id: params[:meme_id], user_id: current_user.id)
    redirect_to :controller => 'memes', :action => 'show', :id => params[:meme_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  # GET /memes
  # GET /memes.json
  def index
    @data = Meme.all.group_by{ |user| user.created_at.to_date }.sort.reverse
  end

  def popular
    @data = Meme.order(votes_count: :desc)
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      @meme.owner = current_user
      if @meme.save
        format.html { redirect_to :action => 'index' }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :edit }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def categories
    @memes_by_categ = Meme.all.group_by { |meme| meme.category.name }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meme_params
      params.require(:meme).permit(:title, :type, :url_source, :votes_count, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  # before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :memes_count)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    Vote.create(meme_id: params[:meme_id], user_id: current_user.id)
    redirect_to :controller => 'memes', :action => 'show', :id => params[:meme_id]
  end

  def unvote
    Vote.find_by(meme_id: params[:meme_id], user_id: current_user.id).destroy
    redirect_to :controller => 'memes', :action => 'show', :id => params[:meme_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/_footer.html.erb
<footer class="flex container justify-center align-items-center">
  <div class="content-footer w-100-percent h-100-percent flex justify-center align-items-center">
    <p>Made by Zamir Narro, Joel Eche & Andrés Del Carpio</p>
  </div>
</footer>

app/views/application/_navbar.html.erb
<header class="container">
  <nav class="flex justify-space-between nav-header">
    <div class="flex">
      <a href="/" class="nav-brand"><%= image_tag "memeable.svg" %></a>
      <ul class="flex nav-list">
        <li class="flex align-items-center">
          <a href="/categories">By Category</a>
        </li>
        <li class="flex align-items-center">
          <a href="/popular">By Popularity</a>
        </li>
        <li class="flex align-items-center">
          <a>Search</a>
        </li>
        <li class="flex align-items-center">
          <a href="/memes/new">Create Meme</a>
        </li>
      </ul>
    </div>

    <div class="flex">
      <ul class="flex nav-list">
        <% if user_signed_in? %>
          <li class="flex align-items-center">
            <%= link_to "My Profile", "/my_profile" %>
          </li>
          <li class="flex align-items-center">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="flex align-items-center">
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/comments/_form.html.erb
<%= form_with(url: "/comments/new", method: "post") do %>
  <%= hidden_field_tag(:meme_id, locals[:meme_id]) %>
  <div>
    <%= text_area_tag :body, nil, required: true, class: 'comment-form w-100-percent' %>
  </div>
  <div class="flex justify-flex-end">
    <%= submit_tag("Comment", class: 'btn-submit') %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memeable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <div class="container">
      <!--<p class="notice"><-%= notice %-></p>-->
      <% if alert %><p class="alert"><%= alert %></p><% end %>
    </div>
    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_with(model: meme, local: true, :html => {:class => 'form-memes mb-30'}) do |form| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
        <% meme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, required: true, class: 'input-text w-100-percent mb-30' %>
  </div>

  <div class="field">
    <%= form.label :type, class: 'label' %>
    <%= form.select(:type, Meme::VALID_TYPE, include_blank: false) %>
  </div>

  <div class="field">
    <%= form.label :url_source, class: 'label' %>
    <%= form.text_field :url_source, required: true, class: 'input-text w-100-percent mb-30' %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: 'label' %>
    <%= form.collection_select :category_id, Category.order(:name),:id,:name, {:include_blank => "Category name"}, required: true %>
  </div>

  <div class="actions mt-30">
    <%= form.submit "Create!", class: 'btn-submit' %>
  </div>
<% end %>

app/views/memes/categories.html.erb
<div class="container">
  <% @memes_by_categ.each do |category, memes| %>
    <h1><%= category %></h1>
    <div class="grid-memes">
      <% memes.each do |meme| %>
        <a href="/memes/<%= meme.id %>" class="meme-item flex align-items-center justify-center">
          <img src="<%= meme.url_source %>" alt="<%= meme.title %>">
        </a>
      <% end %>
    </div>
  <% end %>
</div>

app/views/memes/edit.html.erb
<h1>Editing Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

app/views/memes/index.html.erb
<div class="container">
<% @data.each do |key, memes| %>
  <h1><%= key.strftime('%A, %B %-d') %></h1>
  <div class="grid-memes">
    <% memes.each do |meme| %>
      <a href="/memes/<%=meme.id%>" class="meme-item flex align-items-center justify-center">
          <img src="<%= meme.url_source %>" alt="<%= meme.title %>">
      </a>
    <% end %>
  </div>
  <br>
<% end %>
</div>

app/views/memes/new.html.erb
<div class="container w-30-percent-lg flex flex-column">

  <h1 class="title">Create a meme!</h1>

  <%= render 'form', meme: @meme %>

</div>

app/views/memes/popular.html.erb
<div class="container">
  <h1>Most popular memes</h1>
  <div class="grid-memes">
    <% @data.each do |meme| %>
      <a href="/memes/<%=meme.id%>" class="meme-item flex align-items-center justify-center">
        <img src="<%= meme.url_source %>" alt="<%= meme.title %>">
      </a>
    <% end %>
  </div>
</div>

app/views/memes/show.html.erb
<div class="container flex justify-center flex-column align-items-center meme-detail">
  <h1>
    <%= @meme.title %>
  </h1>

  <img src="<%= @meme.url_source %>" alt="<%= @meme.title %>">

  <div class="flex justify-space-between w-100-percent max-w-440">
    <div class="flex align-items-center">
      <p>
        <strong>Category:</strong>
        <span class="tag-grey"><%= @meme.category.name %></span>
      </p>
    </div>
    <div class="flex align-items-center">
      <p>
        <strong>Votes:</strong>
        <span class="tag-grey"><%= @meme.votes.count %></span>
      </p>
      <% if current_user %>
        <% if vote = Vote.find_by(user: current_user, meme: @meme) %>
          <%= render '/votes/form_update', locals: { meme_id: @meme.id } %>
        <% else %>
          <%= render '/votes/form_new', locals: { meme_id: @meme.id } %>
        <% end %>
      <% else %>
        <p class="require-login vote-message">Login to vote!</p>
      <% end %>
    </div>
  </div>

  <div class="flex justify-space-between w-100-percent max-w-440">
    <div class="flex align-items-center">
      <p>
        <strong>Tags:</strong>
        <% @meme.tags.each do |tag| %>
          <span class="tag-green"><%= tag.name %></span>
        <% end %>
      </p>
    </div>
  </div>

  <div class="comments max-w-440 w-100-percent">
    <h1>Comments:</h1>
    <% if current_user %>
      <%= render '/comments/form', locals: { meme_id: @meme.id } %>
    <% else %>
      <p class="require-login">Login to add a comment!</p>
      <br>
    <% end %>
    <% @meme.comments.each do |comment| %>
      <div class="comment">
        <p><span class="comments__username"><%= comment.user.username %></span></p>
        <p><%= comment.body %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :memes_count %>
    <%= form.number_field :memes_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Memes count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.memes_count %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<main class="container w-30-percent-lg flex flex-column">

  <h1 class="title">My account</h1>

  <div class="user__info">
    <p class="mb-30">
      Username: <%= @user.username %>
    </p>

    <p class="mb-30">
      Email: <%= @user.email %>
    </p>

    <p class="mb-30">
      # of memes: <%= @user.memes_count %>
    </p>

    <%= link_to 'Edit', edit_user_registration_path, class: 'btn-submit text-undecorated edit-profile' %>
  </div>

</main>

app/views/votes/_form_new.html.erb
<%= form_with(url: "/votes/new", method: "post") do %>
  <%= hidden_field_tag(:meme_id, locals[:meme_id]) %>
  <%= submit_tag("Vote", class: 'btn-submit') %>
<% end %>

app/views/votes/_form_update.html.erb
<%= form_with(url: "/votes/unvote", method: "post") do %>
  <%= hidden_field_tag(:meme_id, locals[:meme_id]) %>
  <%= submit_tag("Unvote", class: 'btn-submit') %>
<% end %>